# Generated by Django 4.1 on 2022-08-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anormApp', '0002_post_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=10),
        ),
    ]
