# Generated by Django 4.1 on 2022-08-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='userAddress',
            field=models.TextField(default='집'),
        ),
    ]
