# Generated by Django 4.1 on 2022-08-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anormApp', '0003_alter_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='birth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='name', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='user_id',
            field=models.CharField(default='id', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='user_pw',
            field=models.CharField(default='pw', max_length=20),
        ),
    ]
