# Generated by Django 4.1 on 2022-08-23 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anormApp', '0004_remove_post_text_remove_post_title_post_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='birth',
            new_name='userBirth',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='userName',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_pw',
            new_name='userPW',
        ),
    ]
