# Generated by Django 4.1 on 2022-08-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anormApp', '0005_rename_birth_post_userbirth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='userID',
            field=models.CharField(default='uid', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='userPW',
            field=models.CharField(default='upw', max_length=20),
        ),
    ]
