# Generated by Django 4.1 on 2022-08-30 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbot',
            old_name='sttText',
            new_name='stt_text',
        ),
    ]
